spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/photoPlusDB?useSSL=false
    username: root
    password: pass

server:
  port: 8090

logging:
  level:
    pl:
      polsl:
        photoplus: debug

photoplus:


